name: Auto Commit

on:
  schedule:
    - cron: '* * * * *'  # Runs every 1 minute
  workflow_dispatch:        # Also allows manual trigger

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Git config
        run: |
          git config --global user.email "your-email@example.com"
          git config --global user.name "Auto Commit Bot"

      - name: Make changes (optional)
        run: |
          echo "// Auto commit at $(date)" >> auto-commit-log.txt

      - name: Commit and push
        run: |
          git add .
          git commit -m "Auto commit at $(date)" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} HEAD:main
